CREATE DATABASE IF NOT EXISTS login_test;

USE login_test;

CREATE TABLE IF NOT EXISTS Tb_Usuario (
    Usu_id INT AUTO_INCREMENT PRIMARY KEY,
    Usu_nome VARCHAR(255) NOT NULL,
    Usu_email VARCHAR(255) NOT NULL UNIQUE,
    Usu_senha VARCHAR(255) NOT NULL,
    Usu_cpf VARCHAR(16) NOT NULL UNIQUE,
    Usu_genero CHAR(1) NOT NULL,
    Usu_foto VARCHAR(255) NOT NULL,
    Usu_datacriacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Usu_statusonline VARCHAR(16) NOT NULL,
    Usu_ultimaonline TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);